CREATE TABLE materiel(
        identifiant      TEXT NOT NULL,
        type_objet       TEXT,
        m_type_materiel    TEXT,       
        m_numero_inventaire TEXT,       
        m_nom_site         TEXT,
        m_localite         TEXT,
        m_commune          TEXT,
        m_region           TEXT,
        m_pays             TEXT,
        m_nom_commun       TEXT,
        m_inventeur        TEXT,
        m_donnateur        TEXT,
        m_depot_original   TEXT,
        m_date_decouverte  TEXT,
        m_periode_culturelle TEXT,
        m_periode_geologique TEXT,
        m_age_absolu       TEXT,
        m_date_copie       TEXT,
        m_numero_individu  TEXT,
        m_classe           TEXT,
        m_ordre            TEXT,
        m_famille          TEXT,
        m_genre            TEXT,
        m_espece           TEXT,
        m_nom_vernaculaire TEXT,
        m_synonymes        TEXT,
        m_age_individu     TEXT,
        m_sexe_individu    TEXT,
        m_donnees_individu TEXT,
        m_representation_squel    TEXT,
        m_description_anatomique  TEXT,
        m_observations_anatomique TEXT,
        m_nature           TEXT,
        m_observations     TEXT,
        m_bibliographie    TEXT,
        m_mots_clefs       TEXT,
        m_type_support     TEXT,
        m_auteur           TEXT,
        m_titre            TEXT,     
        m_editeur          TEXT,
        m_date_edition     TEXT,
        m_duree            TEXT,
        m_dimensions       TEXT,
        m_echelle          TEXT,
        m_piece            TEXT,     
        m_meuble           TEXT,
        m_tiroir           TEXT,
        m_etagere          TEXT,
        m_nombre_exemplaires INT,
        m_date_modif       DATE,     
        PRIMARY KEY (identifiant)
);

GRANT ALL ON materiel TO supercollection;
GRANT ALL ON materiel TO collection;
GRANT SELECT ON materiel TO supercollection;

