#! /usr/bin/env python

import sys
import os

for fichier in os.listdir(".") :
    if fichier.endswith(".datas") :
        nom = fichier[:-6]
        print "Traitement de %s..." % fichier,
        sys.stdout.flush()
        os.system("../genmap --titre %s config-arago-transversale %s >%s.pdf 2>erreurs-%s.html" % (nom, fichier, nom, nom))
        print
